/**
 * eatsight-api
 * This is a API document for EatSight
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Item;
import io.swagger.client.model.Page;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetFoodsResponse {
  
  @SerializedName("page")
  private Page page = null;
  @SerializedName("items")
  private List<Item> items = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Page getPage() {
    return page;
  }
  public void setPage(Page page) {
    this.page = page;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Item> getItems() {
    return items;
  }
  public void setItems(List<Item> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFoodsResponse getFoodsResponse = (GetFoodsResponse) o;
    return (this.page == null ? getFoodsResponse.page == null : this.page.equals(getFoodsResponse.page)) &&
        (this.items == null ? getFoodsResponse.items == null : this.items.equals(getFoodsResponse.items));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.page == null ? 0: this.page.hashCode());
    result = 31 * result + (this.items == null ? 0: this.items.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFoodsResponse {\n");
    
    sb.append("  page: ").append(page).append("\n");
    sb.append("  items: ").append(items).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
