/**
 * eatsight-api
 * This is a API document for EatSight
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Nutrient;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Item {
  
  @SerializedName("foodId")
  private String foodId = null;
  @SerializedName("mainNutrientServingMeasureAmount")
  private String mainNutrientServingMeasureAmount = null;
  @SerializedName("foodName")
  private String foodName = null;
  @SerializedName("vendors")
  private String vendors = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("foodType")
  private String foodType = null;
  @SerializedName("volume")
  private String volume = null;
  @SerializedName("mainNutrientServingMeasureUnit")
  private String mainNutrientServingMeasureUnit = null;
  @SerializedName("registerDate")
  private String registerDate = null;
  @SerializedName("thumbnailUrl")
  private String thumbnailUrl = null;
  @SerializedName("volumeUnit")
  private String volumeUnit = null;
  @SerializedName("mainNutrients")
  private List<Nutrient> mainNutrients = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFoodId() {
    return foodId;
  }
  public void setFoodId(String foodId) {
    this.foodId = foodId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMainNutrientServingMeasureAmount() {
    return mainNutrientServingMeasureAmount;
  }
  public void setMainNutrientServingMeasureAmount(String mainNutrientServingMeasureAmount) {
    this.mainNutrientServingMeasureAmount = mainNutrientServingMeasureAmount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFoodName() {
    return foodName;
  }
  public void setFoodName(String foodName) {
    this.foodName = foodName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVendors() {
    return vendors;
  }
  public void setVendors(String vendors) {
    this.vendors = vendors;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFoodType() {
    return foodType;
  }
  public void setFoodType(String foodType) {
    this.foodType = foodType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVolume() {
    return volume;
  }
  public void setVolume(String volume) {
    this.volume = volume;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMainNutrientServingMeasureUnit() {
    return mainNutrientServingMeasureUnit;
  }
  public void setMainNutrientServingMeasureUnit(String mainNutrientServingMeasureUnit) {
    this.mainNutrientServingMeasureUnit = mainNutrientServingMeasureUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegisterDate() {
    return registerDate;
  }
  public void setRegisterDate(String registerDate) {
    this.registerDate = registerDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getThumbnailUrl() {
    return thumbnailUrl;
  }
  public void setThumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVolumeUnit() {
    return volumeUnit;
  }
  public void setVolumeUnit(String volumeUnit) {
    this.volumeUnit = volumeUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Nutrient> getMainNutrients() {
    return mainNutrients;
  }
  public void setMainNutrients(List<Nutrient> mainNutrients) {
    this.mainNutrients = mainNutrients;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return (this.foodId == null ? item.foodId == null : this.foodId.equals(item.foodId)) &&
        (this.mainNutrientServingMeasureAmount == null ? item.mainNutrientServingMeasureAmount == null : this.mainNutrientServingMeasureAmount.equals(item.mainNutrientServingMeasureAmount)) &&
        (this.foodName == null ? item.foodName == null : this.foodName.equals(item.foodName)) &&
        (this.vendors == null ? item.vendors == null : this.vendors.equals(item.vendors)) &&
        (this.barcode == null ? item.barcode == null : this.barcode.equals(item.barcode)) &&
        (this.foodType == null ? item.foodType == null : this.foodType.equals(item.foodType)) &&
        (this.volume == null ? item.volume == null : this.volume.equals(item.volume)) &&
        (this.mainNutrientServingMeasureUnit == null ? item.mainNutrientServingMeasureUnit == null : this.mainNutrientServingMeasureUnit.equals(item.mainNutrientServingMeasureUnit)) &&
        (this.registerDate == null ? item.registerDate == null : this.registerDate.equals(item.registerDate)) &&
        (this.thumbnailUrl == null ? item.thumbnailUrl == null : this.thumbnailUrl.equals(item.thumbnailUrl)) &&
        (this.volumeUnit == null ? item.volumeUnit == null : this.volumeUnit.equals(item.volumeUnit)) &&
        (this.mainNutrients == null ? item.mainNutrients == null : this.mainNutrients.equals(item.mainNutrients));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.foodId == null ? 0: this.foodId.hashCode());
    result = 31 * result + (this.mainNutrientServingMeasureAmount == null ? 0: this.mainNutrientServingMeasureAmount.hashCode());
    result = 31 * result + (this.foodName == null ? 0: this.foodName.hashCode());
    result = 31 * result + (this.vendors == null ? 0: this.vendors.hashCode());
    result = 31 * result + (this.barcode == null ? 0: this.barcode.hashCode());
    result = 31 * result + (this.foodType == null ? 0: this.foodType.hashCode());
    result = 31 * result + (this.volume == null ? 0: this.volume.hashCode());
    result = 31 * result + (this.mainNutrientServingMeasureUnit == null ? 0: this.mainNutrientServingMeasureUnit.hashCode());
    result = 31 * result + (this.registerDate == null ? 0: this.registerDate.hashCode());
    result = 31 * result + (this.thumbnailUrl == null ? 0: this.thumbnailUrl.hashCode());
    result = 31 * result + (this.volumeUnit == null ? 0: this.volumeUnit.hashCode());
    result = 31 * result + (this.mainNutrients == null ? 0: this.mainNutrients.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("  foodId: ").append(foodId).append("\n");
    sb.append("  mainNutrientServingMeasureAmount: ").append(mainNutrientServingMeasureAmount).append("\n");
    sb.append("  foodName: ").append(foodName).append("\n");
    sb.append("  vendors: ").append(vendors).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  foodType: ").append(foodType).append("\n");
    sb.append("  volume: ").append(volume).append("\n");
    sb.append("  mainNutrientServingMeasureUnit: ").append(mainNutrientServingMeasureUnit).append("\n");
    sb.append("  registerDate: ").append(registerDate).append("\n");
    sb.append("  thumbnailUrl: ").append(thumbnailUrl).append("\n");
    sb.append("  volumeUnit: ").append(volumeUnit).append("\n");
    sb.append("  mainNutrients: ").append(mainNutrients).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
