/**
 * eatsight-api
 * This is a API document for EatSight
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Nutrient {
  
  @SerializedName("servingAmount")
  private String servingAmount = null;
  @SerializedName("servingAmountUnit")
  private String servingAmountUnit = null;
  @SerializedName("rate")
  private String rate = null;
  @SerializedName("nutrientName")
  private String nutrientName = null;
  @SerializedName("nutrientId")
  private String nutrientId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getServingAmount() {
    return servingAmount;
  }
  public void setServingAmount(String servingAmount) {
    this.servingAmount = servingAmount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getServingAmountUnit() {
    return servingAmountUnit;
  }
  public void setServingAmountUnit(String servingAmountUnit) {
    this.servingAmountUnit = servingAmountUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRate() {
    return rate;
  }
  public void setRate(String rate) {
    this.rate = rate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNutrientName() {
    return nutrientName;
  }
  public void setNutrientName(String nutrientName) {
    this.nutrientName = nutrientName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNutrientId() {
    return nutrientId;
  }
  public void setNutrientId(String nutrientId) {
    this.nutrientId = nutrientId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Nutrient nutrient = (Nutrient) o;
    return (this.servingAmount == null ? nutrient.servingAmount == null : this.servingAmount.equals(nutrient.servingAmount)) &&
        (this.servingAmountUnit == null ? nutrient.servingAmountUnit == null : this.servingAmountUnit.equals(nutrient.servingAmountUnit)) &&
        (this.rate == null ? nutrient.rate == null : this.rate.equals(nutrient.rate)) &&
        (this.nutrientName == null ? nutrient.nutrientName == null : this.nutrientName.equals(nutrient.nutrientName)) &&
        (this.nutrientId == null ? nutrient.nutrientId == null : this.nutrientId.equals(nutrient.nutrientId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.servingAmount == null ? 0: this.servingAmount.hashCode());
    result = 31 * result + (this.servingAmountUnit == null ? 0: this.servingAmountUnit.hashCode());
    result = 31 * result + (this.rate == null ? 0: this.rate.hashCode());
    result = 31 * result + (this.nutrientName == null ? 0: this.nutrientName.hashCode());
    result = 31 * result + (this.nutrientId == null ? 0: this.nutrientId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Nutrient {\n");
    
    sb.append("  servingAmount: ").append(servingAmount).append("\n");
    sb.append("  servingAmountUnit: ").append(servingAmountUnit).append("\n");
    sb.append("  rate: ").append(rate).append("\n");
    sb.append("  nutrientName: ").append(nutrientName).append("\n");
    sb.append("  nutrientId: ").append(nutrientId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
